server:
  port: 7111

eureka:
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    renewalThresholdUpdateIntervalMs: 5000
    use-read-only-response-cache: false