server:
  port: 7120
  max-http-header-size: 20480
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/quartztest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true&useSSL=false&allowMultiQueries=true
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver